name: CD

on: 
  push:
    branches: 
      - release

jobs:
  test:
    
    runs-on: [ubuntu-latest]
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
        
      - name: Launch flutter tests
        uses: steebchen/flutter@v1.0.0
        with:
          args: test
   
  build-web:
    needs: test
    runs-on: [ubuntu-latest]
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
        
      - name: Build flutter for web
        uses: steebchen/flutter@v1.0.0
        with:
          args: build web
          
  deploy-web:
    needs: build-web
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
        
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
