name: CD

on: 
  push:
    branches: 
      - release

jobs:
  test:
    
    runs-on: [ubuntu-latest]
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
        
      - name: Launch flutter tests
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.1'
          channel: 'dev'
      - run: flutter test --coverage
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage/lcov.info
   
  build-web:
    needs: test
    runs-on: [ubuntu-latest]
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
        
      - name: Build flutter for web
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.1'
          channel: 'dev'
      - run: flutter upgrade
      - run: flutter config --enable-web
      - run: flutter build web
          
  deploy-web:
    needs: build-web
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
        
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
